name: GHARerunTest
    
on:
#   push:
#     branches: ['master']
#   pull_request:
#     branches: ['master']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
            
      # - name: ServiceNow DevOps Sonar Scan Results
      #   uses: ServiceNow/servicenow-devops-sonar@v3.1.0
      #   with:
      #     devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     job-name: 'Build'
      #     context-github: ${{ toJSON(github) }}
      #     sonar-host-url: ${{ secrets.SONAR_URL }}
      #     sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
      
      # - name: Run JUnit Tests
      #   run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
        
      # - name: ServiceNow DevOps Unit Test Results
      #   uses: ServiceNow/servicenow-devops-test-report@v1.34.2
      #   with:
      #     devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
      #     devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     context-github: ${{ toJSON(github) }}
      #     job-name: 'Build'
      #     xml-report-filename: target/surefire-reports/testng-results.xml
          
  # integrationTest:
  #   needs: build
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
  #   steps:  
  #     - name: Register Artifact
  #       uses: ServiceNow/servicenow-devops-register-artifact@v1.34.2
  #       with:
  #         devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
  #         devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
  #         instance-url: ${{ secrets.SN_INSTANCE_URL }}
  #         tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
  #         context-github: ${{ toJSON(github) }}
  #         job-name: 'Integration Tests'
  #         artifacts: ' [{"name": "com:autoclaim","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'

      # - name: Register Package
      #   uses: ServiceNow/servicenow-devops-register-package@v1.34.2
      #   with:
      #     devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
      #     devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     context-github: ${{ toJSON(github) }}
      #     job-name: 'Integration Tests'
      #     artifacts: ' [{"name": "com:autoclaim","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'
      #     package-name: 'autoclaim.war'
      
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:     
      - name: Custom Change
        uses: ServiceNow/servicenow-devops-change@v4.0.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Deploy'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018"}}'
          interval: '100'
          timeout: '3600'
          
      - name: Run deployment scripts
        run: echo Completed Deployment.
      # - name: Sleep
      #   run: sleep 15

  postDeploy:
    needs: deploy
    name: Post Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 15

      - name: ServiceNow DevOps Get Change
        uses: aviskalange/servicenow-devops-get-change@main
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          # The inputs to identify change at Servicenow and GET it.
          change-details: '{"build_number":"${{ github.run_id }}","pipeline_name":"aviskalange/DevOpsIntegration/GHARerunTest","stage_name":"Deploy", "attempt_number": ""}'
          
